/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DictionariesIndexRouteImport } from './routes/dictionaries.index'
import { Route as DictionariesDictionaryNameIndexRouteImport } from './routes/dictionaries.$dictionaryName.index'
import { Route as DictionariesDictionaryNameFeaturesFeatureIndexRouteImport } from './routes/dictionaries.$dictionaryName.features.$featureIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionariesIndexRoute = DictionariesIndexRouteImport.update({
  id: '/dictionaries/',
  path: '/dictionaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionariesDictionaryNameIndexRoute =
  DictionariesDictionaryNameIndexRouteImport.update({
    id: '/dictionaries/$dictionaryName/',
    path: '/dictionaries/$dictionaryName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DictionariesDictionaryNameFeaturesFeatureIndexRoute =
  DictionariesDictionaryNameFeaturesFeatureIndexRouteImport.update({
    id: '/dictionaries/$dictionaryName/features/$featureIndex',
    path: '/dictionaries/$dictionaryName/features/$featureIndex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictionaries': typeof DictionariesIndexRoute
  '/dictionaries/$dictionaryName': typeof DictionariesDictionaryNameIndexRoute
  '/dictionaries/$dictionaryName/features/$featureIndex': typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictionaries': typeof DictionariesIndexRoute
  '/dictionaries/$dictionaryName': typeof DictionariesDictionaryNameIndexRoute
  '/dictionaries/$dictionaryName/features/$featureIndex': typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictionaries/': typeof DictionariesIndexRoute
  '/dictionaries/$dictionaryName/': typeof DictionariesDictionaryNameIndexRoute
  '/dictionaries/$dictionaryName/features/$featureIndex': typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictionaries'
    | '/dictionaries/$dictionaryName'
    | '/dictionaries/$dictionaryName/features/$featureIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dictionaries'
    | '/dictionaries/$dictionaryName'
    | '/dictionaries/$dictionaryName/features/$featureIndex'
  id:
    | '__root__'
    | '/'
    | '/dictionaries/'
    | '/dictionaries/$dictionaryName/'
    | '/dictionaries/$dictionaryName/features/$featureIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictionariesIndexRoute: typeof DictionariesIndexRoute
  DictionariesDictionaryNameIndexRoute: typeof DictionariesDictionaryNameIndexRoute
  DictionariesDictionaryNameFeaturesFeatureIndexRoute: typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionaries/': {
      id: '/dictionaries/'
      path: '/dictionaries'
      fullPath: '/dictionaries'
      preLoaderRoute: typeof DictionariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionaries/$dictionaryName/': {
      id: '/dictionaries/$dictionaryName/'
      path: '/dictionaries/$dictionaryName'
      fullPath: '/dictionaries/$dictionaryName'
      preLoaderRoute: typeof DictionariesDictionaryNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionaries/$dictionaryName/features/$featureIndex': {
      id: '/dictionaries/$dictionaryName/features/$featureIndex'
      path: '/dictionaries/$dictionaryName/features/$featureIndex'
      fullPath: '/dictionaries/$dictionaryName/features/$featureIndex'
      preLoaderRoute: typeof DictionariesDictionaryNameFeaturesFeatureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictionariesIndexRoute: DictionariesIndexRoute,
  DictionariesDictionaryNameIndexRoute: DictionariesDictionaryNameIndexRoute,
  DictionariesDictionaryNameFeaturesFeatureIndexRoute:
    DictionariesDictionaryNameFeaturesFeatureIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
