/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DictionariesIndexRouteImport } from './routes/dictionaries.index'
import { Route as CircuitsIndexRouteImport } from './routes/circuits.index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DictionariesDictionaryNameIndexRouteImport } from './routes/dictionaries.$dictionaryName.index'
import { Route as DictionariesDictionaryNameFeaturesFeatureIndexRouteImport } from './routes/dictionaries.$dictionaryName.features.$featureIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionariesIndexRoute = DictionariesIndexRouteImport.update({
  id: '/dictionaries/',
  path: '/dictionaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsIndexRoute = CircuitsIndexRouteImport.update({
  id: '/circuits/',
  path: '/circuits/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionariesDictionaryNameIndexRoute =
  DictionariesDictionaryNameIndexRouteImport.update({
    id: '/dictionaries/$dictionaryName/',
    path: '/dictionaries/$dictionaryName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DictionariesDictionaryNameFeaturesFeatureIndexRoute =
  DictionariesDictionaryNameFeaturesFeatureIndexRouteImport.update({
    id: '/dictionaries/$dictionaryName/features/$featureIndex',
    path: '/dictionaries/$dictionaryName/features/$featureIndex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/circuits': typeof CircuitsIndexRoute
  '/dictionaries': typeof DictionariesIndexRoute
  '/dictionaries/$dictionaryName': typeof DictionariesDictionaryNameIndexRoute
  '/dictionaries/$dictionaryName/features/$featureIndex': typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/circuits': typeof CircuitsIndexRoute
  '/dictionaries': typeof DictionariesIndexRoute
  '/dictionaries/$dictionaryName': typeof DictionariesDictionaryNameIndexRoute
  '/dictionaries/$dictionaryName/features/$featureIndex': typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/dictionaries/': typeof DictionariesIndexRoute
  '/dictionaries/$dictionaryName/': typeof DictionariesDictionaryNameIndexRoute
  '/dictionaries/$dictionaryName/features/$featureIndex': typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/circuits'
    | '/dictionaries'
    | '/dictionaries/$dictionaryName'
    | '/dictionaries/$dictionaryName/features/$featureIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/circuits'
    | '/dictionaries'
    | '/dictionaries/$dictionaryName'
    | '/dictionaries/$dictionaryName/features/$featureIndex'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/bookmarks/'
    | '/circuits/'
    | '/dictionaries/'
    | '/dictionaries/$dictionaryName/'
    | '/dictionaries/$dictionaryName/features/$featureIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
  CircuitsIndexRoute: typeof CircuitsIndexRoute
  DictionariesIndexRoute: typeof DictionariesIndexRoute
  DictionariesDictionaryNameIndexRoute: typeof DictionariesDictionaryNameIndexRoute
  DictionariesDictionaryNameFeaturesFeatureIndexRoute: typeof DictionariesDictionaryNameFeaturesFeatureIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionaries/': {
      id: '/dictionaries/'
      path: '/dictionaries'
      fullPath: '/dictionaries'
      preLoaderRoute: typeof DictionariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/': {
      id: '/circuits/'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionaries/$dictionaryName/': {
      id: '/dictionaries/$dictionaryName/'
      path: '/dictionaries/$dictionaryName'
      fullPath: '/dictionaries/$dictionaryName'
      preLoaderRoute: typeof DictionariesDictionaryNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionaries/$dictionaryName/features/$featureIndex': {
      id: '/dictionaries/$dictionaryName/features/$featureIndex'
      path: '/dictionaries/$dictionaryName/features/$featureIndex'
      fullPath: '/dictionaries/$dictionaryName/features/$featureIndex'
      preLoaderRoute: typeof DictionariesDictionaryNameFeaturesFeatureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
  CircuitsIndexRoute: CircuitsIndexRoute,
  DictionariesIndexRoute: DictionariesIndexRoute,
  DictionariesDictionaryNameIndexRoute: DictionariesDictionaryNameIndexRoute,
  DictionariesDictionaryNameFeaturesFeatureIndexRoute:
    DictionariesDictionaryNameFeaturesFeatureIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
