import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Check, Edit2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useRouter } from '@tanstack/react-router'
import type { Feature } from '@/types/feature'
import { updateInterpretation } from '@/api/features'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Info } from '@/components/ui/info'
import { Textarea } from '@/components/ui/textarea'

type FeatureInterpretationProps = {
  feature: Feature
  dictionaryName: string
  featureIndex: number
}

export function FeatureInterpretation({
  feature,
  dictionaryName,
  featureIndex,
}: FeatureInterpretationProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [editText, setEditText] = useState(feature.interpretation?.text || '')

  useEffect(() => {
    setEditText(feature.interpretation?.text || '')
  }, [feature.interpretation?.text])

  const queryClient = useQueryClient()
  const router = useRouter()
  const updateMutation = useMutation({
    mutationFn: updateInterpretation,
    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey: ['feature', dictionaryName, featureIndex],
      })
      await router.invalidate({ sync: true })
      setIsEditing(false)
    },
  })

  const handleSave = () => {
    if (editText.trim()) {
      updateMutation.mutate({
        data: {
          dictionaryName,
          featureIndex,
          text: editText.trim(),
        },
      })
    }
  }

  const handleCancel = () => {
    setEditText(feature.interpretation?.text || '')
    setIsEditing(false)
  }

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="font-semibold tracking-tight flex justify-center items-center text-sm text-slate-700 gap-1 cursor-default">
          EXPLANATIONS{' '}
          <Info iconSize={14}>
            <b>Automated Interpretation</b> generated by LLMs through looking at
            the top activations of the feature.
          </Info>
        </CardTitle>
      </CardHeader>
      <CardContent>
        {!isEditing && (
          <div className="flex items-start justify-between gap-2">
            <div className="flex-1 min-w-0">
              {!feature.interpretation && (
                <p className="text-neutral-500">No interpretation available.</p>
              )}
              {feature.interpretation && (
                <div className="font-token text-sm rounded-md w-fit">
                  {feature.interpretation.text}
                </div>
              )}
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8 shrink-0"
              onClick={() => setIsEditing(true)}
              aria-label="Edit interpretation"
            >
              <Edit2 className="h-4 w-4 text-slate-500" />
            </Button>
          </div>
        )}

        {isEditing && (
          <div className="space-y-3">
            <Textarea
              value={editText}
              onChange={(e) => setEditText(e.target.value)}
              placeholder="Enter interpretation..."
              className="min-h-[80px] font-token text-sm"
              disabled={updateMutation.isPending}
            />
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                onClick={handleSave}
                disabled={updateMutation.isPending || !editText.trim()}
                className="h-8"
              >
                <Check className="h-4 w-4 mr-1" />
                Save
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={handleCancel}
                disabled={updateMutation.isPending}
                className="h-8"
              >
                <X className="h-4 w-4 mr-1" />
                Cancel
              </Button>
              {updateMutation.isPending && (
                <span className="text-xs text-slate-500">Saving...</span>
              )}
              {updateMutation.isError && (
                <span className="text-xs text-red-500">
                  {updateMutation.error instanceof Error
                    ? updateMutation.error.message
                    : 'Failed to save'}
                </span>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
